version: '3.7'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - production.env
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
      - type: bind
        source: ./db/data
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./db/config/10_max-allowed-packet.cnf
        target: /etc/mysql/mysql.conf.d/10_max-allowed-packet.cnf
  apache:
    image: lifein19x19:7.1-apache
    build:
      context: .
      dockerfile: Dockerfile.php
    hostname: "${ENVIRONMENT_NAME}"
    ports:
      - "8080:80"
    env_file:
      - production.env
    volumes:
      - type: bind
        source: ./forum
        target: /var/www/html
      - type: volume
        source: cache
        target: /var/www/html/cache
      - type: bind
        source: ./data/images
        target: /var/www/html/images
      - type: bind
        source: ./data/files
        target: /var/www/html/files
    links:
      - mysql

volumes:
  data:
  cache:
