version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
      - type: bind
        source: ./db/data
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./db/config/10_max-allowed-packet.cnf
        target: /etc/mysql/mysql.conf.d/10_max-allowed-packet.cnf
      - type: bind
        source: ./db/config/11_db-mode.cnf
        target: /etc/mysql/mysql.conf.d/11_db-mode.cnf
      - type: bind
        source: ./db/config/12_utf8.cnf
        target: /etc/mysql/mysql.conf.d/12_utf8.cnf
    networks:
      - default
    restart: unless-stopped

  apache:
    image: lifein19x19:7.1-apache
    build:
      context: .
      dockerfile: Dockerfile.php
    labels:
      traefik.enable: "true"
      traefik.http.routers.l19.rule: "HostRegexp(`{host:^(www\\.)?(${ENVIRONMENT_NAME}\\.)?lifein19x19.com(:\\d+)?$$}`)"
      traefik.http.routers.l19.tls.certResolver: "r53resolver"
      traefik.http.routers.l19.tls.domains[0].main: "lifein19x19.com"
      traefik.http.routers.l19.tls.domains[0].sans: "www.lifein19x19.com,prod.lifein19x19.com,www.prod.lifein19x19.com"
      traefik.http.middlewares.l19forumprefix.stripprefix.prefixes: "/forum"
      traefik.http.routers.l19.middlewares: "l19forumprefix"
      traefik.docker.network: proxy
    hostname: "${ENVIRONMENT_NAME}"
    ports:
      - "${HOST_PORT}:80"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
      - APACHE_RUN_USER=${APACHE_RUN_USER}
      - APACHE_RUN_GROUP=${APACHE_RUN_GROUP}
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./forum
        target: /var/www/html
      - type: volume
        source: cache
        target: /var/www/html/cache
      - type: bind
        source: ./data/images
        target: /var/www/html/images
      - type: bind
        source: ./data/files
        target: /var/www/html/files
    networks:
      - default
      - proxy


volumes:
  data:
  cache:

networks:
  default:
  proxy:
    external: true
